### ISSUE TITLE
Conform to REST

### ISSUE THREAD

**Issue by yossarianirving** [yossarianirving/CSC440Server#5]
https://github.com/yossarianirving/CSC440Server/blob/b4970eabfa6c6f875585850a55106ab343286609/src/main/java/GradeApi/CourseController.java#L66

Should be `@PatchMapping("{id}")`

https://github.com/yossarianirving/CSC440Server/blob/b4970eabfa6c6f875585850a55106ab343286609/src/main/java/GradeApi/CourseController.java#L145

Should be `@DeleteMapping("{id"})` and there is no request body for delete/

Same goes for patch and delete on the assignment controller

**Comment by CodeCrazy97** [comment]
Well, don't you need to provide the update information for the modified course? (i.e. if you change the number of credits, you'd need to provide the new information for the UPDATE clause in the SQL statement.) Also, do you want me to return the course/assignment after it has been deleted (**return new ResponseEntity<>(assignment, HttpStatus.OK);**)

**Comment by CodeCrazy97** [comment]
Ah, sorry... I missed that you said "there is no request body for delete" (I assume there still is one for patch)

**Comment by CodeCrazy97** [comment]
However...I am still wondering what the return type should be for the delete mapping?

**Comment by CodeCrazy97** [comment]
Do I

**Comment by CodeCrazy97** [comment]
Could you tell me what's wrong with my method declaration?

**@DeleteMapping("{id}")
    public ResponseEntity<Course> deleteAssignment(@Param("id") String id) throws Exception {**

**Comment by CodeCrazy97** [comment]
(That @Param is actually uppercase in my code...dunno why it's not here.)
In Postman, I keep getting "Request method 'DELETE' not supported". 

Here is what I passed:
![image](https://user-images.githubusercontent.com/39338996/69501158-3269c380-0ed0-11ea-8877-e2db758bd4b7.png)

(this failed even after I added a JSON body with "id": 5)

**Comment by yossarianirving** [comment]
There is no classID get parameter. The Id follows the slash. DELETE
/courses/2 should delete course 2.
